name: "Build"
on:
  push:
    paths:
      - 'flake.lock'
  workflow_dispatch:

jobs:

  build-amd64:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [amd64]
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: propheci
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: |
        nix build .#packages.x86_64-linux.telegram-desktop-userfonts -L

  build-arm64:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [arm64]
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: propheci
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: |
        nix build .#packages.aarch64-linux.telegram-desktop-userfonts -L
