name: "Build"
on:
  push:
    paths:
      - 'flake.lock'
  workflow_dispatch:

jobs:

  build-amd64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: propheci
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: |
        nix build .#packages.x86_64-linux.default -L

  # build-arm64:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #   - run: sudo apt-get install -y qemu-user-static
  #   - uses: cachix/install-nix-action@v25
  #     with:
  #       nix_path: nixpkgs=channel:nixos-unstable
  #       extra_nix_config: |
  #         system = aarch64-linux
  #   - uses: cachix/cachix-action@v14
  #     with:
  #       name: propheci
  #       authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
  #   - run: |
  #       nix build .#packages.aarch64-linux.telegram-desktop-userfonts -L
