name: "Build"
on:
  push:
    paths:
      - 'flake.lock'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: propheci
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: |
        # x86_64-linux
        nix build .#packages.x86_64-linux.telegram-desktop-userfonts -L

        # aarch64-linux
        # nix build .#packages.aarch64-linux.telegram-desktop-userfonts -L --arg crossSystem '{ config = "aarch64-unknown-linux-gnu"; }';
