name: "Build"
on:
  push:
    paths:
      - 'flake.lock'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: propheci
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: |
        for system in "aarch64-linux" "x86_64-linux"; do
          nix build .#packages.$system.telegram-desktop-userfonts -L
        done
